version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

  jobs:
    pre_build:
      - "mkdir -p ./docs/notebooks"
      - "cp ./examples/notebooks/*.ipynb ./docs/notebooks"
      - "pip install -r ./docs/requirements.txt"
      # Build the MkDocs site
      # - "mike deploy --push --update-aliases 1.0 latest"

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Dependencies required to build your docs
python:
   install:
   - requirements: docs/requirements.txt
   - method: pip
     path: .