name: CI Pipeline

on:
  push:
    branches:
      - helix-notebook-updates

jobs:
  coverage:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.8

      - name: Install dependencies
        run: |
            pip install -r requirements-dev.txt
            pip install .[mamba-ssm]
            
      # First download before tests as they make use of the downloaded files 
      - name: Download all files
        run: |
          python ci/download_all.py

      - name: Execute unit tests to get coverage
        run: |
          CUDA_VISIBLE_DEVICES=-1 pytest --cov=helical ci/

      - name: Generate coverage badge
        uses: tj-actions/coverage-badge-py@v2
      
      - name: Verify coverage badge changed
        uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
        with:
          files: coverage.svg

      - name: Commit files
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          rm -f assets/coverage.svg
          git add -u assets/
          git commit -m "Remove old coverage badge"
          mv coverage.svg assets/
          git add assets/coverage.svg
          git commit -m "Add new coverage badge"
          git push

